In [1]:
import numpy as np

list_1 = [10.0, 5.0, 1.0]
print(list_1)
type(list_1)

[10.0, 5.0, 1.0]


list

In [2]:
list_2 = np.array(list_1)
print(list_2)
type(list_2)

[10.  5.  1.]


numpy.ndarray

In [4]:
x = np.array([[1.0, 2.0, 3.0],
            [1.0, 2.0, 3.0],
            [1.0, 2.0, 3.0]])

y = np.array([[1.0, 1.0, 1.0],
             [2.0, 2.0, 2.0],
             [3.0, 3.0, 3.0]])

x + y

array([[2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [5]:
x = np.array([[1.0, 2.0, 3.0],
            [1.0, 2.0, 3.0],
            [1.0, 2.0, 3.0]])

y = np.array([[1.0, 1.0, 1.0],
             [2.0, 2.0, 2.0],
             [3.0, 3.0, 3.0]])

x * y

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])