In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
A.shape

(2, 2)

In [4]:
A.dtype

dtype('int32')

In [6]:
A*10

array([[10, 20],
       [30, 40]])

In [18]:
np.array([[10,10],[10,10]])*A

array([[10, 20],
       [30, 40]])

In [19]:
A = np.array([[1,2], [3,4]]) # 2x2
B = np.array([10, 20]) # 1x2 -> 2x2
A * B

array([[10, 40],
       [30, 80]])

In [21]:
A = np.array([[1,2], [3,4]]) # 2x2
B = np.array([[10, 20], [10, 20]]) # 1x2 -> 2x2
A * B

array([[10, 40],
       [30, 80]])

In [33]:
A-1

array([[0, 1],
       [2, 3]])

In [32]:
A/1

array([[1., 2.],
       [3., 4.]])

In [34]:
A+2

array([[3, 4],
       [5, 6]])

In [35]:
X = np.array([[51, 55], [14, 19], [0, 4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [37]:
X[0][1]

55

In [58]:
X[[0],1]

array([55])

In [79]:
X[[0]]

array([[51, 55]])

In [59]:
X[[0],[1]]

array([55])

In [49]:
X[0,1]

55

In [50]:
X[[0],1]

array([55])

In [72]:
X[[0,1]]

array([[51, 55],
       [14, 19]])

In [75]:
X[[0, 1], :]

array([[51, 55],
       [14, 19]])

In [74]:
X[[0, 1], 0]

array([51, 14])

In [78]:
X[[False, True, False]]

array([[14, 19]])

In [101]:
b = np.array([[1, 2],
               [3, 4],
               [ 5, 6]])
a = b[:2,:]
print(a)
print('\n')
a[0] = [100, 100]
print(a)
print('\n')
print(b)

[[1 2]
 [3 4]]


[[100 100]
 [  3   4]]


[[100 100]
 [  3   4]
 [  5   6]]


In [102]:
b = np.array([[1, 2],
               [3, 4],
               [ 5, 6]])
a = b[[0,1], :]

print(a)
print('\n')
a[0,:] = [100, 100]
print(a)
print('\n')
print(b)

[[1 2]
 [3 4]]


[[100 100]
 [  3   4]]


[[1 2]
 [3 4]
 [5 6]]
